name: 'Keep last N releases'
description: 'A GitHub Action to keep only the last N releases'
inputs:
  n:
    description: 'Number of releases to keep'
    required: true
  last_tag_file:
    description: 'File containing the tag of the last successful release, which should not be deleted'
    required: false
    default: ''
  remove_tags_without_release:
    description: 'Remove tags which do not have an associated release'
    required: false
    default: 'false'
  dry_run:
    description: 'Do not actually delete releases'
    required: false
    default: 'false'

runs:
  using: 'node20'
  main: 'dist/index.js'
